In [1]:
import torch
from torch import nn

In [2]:
img=torch.tensor([[1,2],
                 [3,4]])

In [3]:
img

tensor([[1, 2],
        [3, 4]])

$S_{out}=(S_{in}-1)*stride-2*padding+(k-1)+padding_{output}+1$

In [4]:
m=nn.ConvTranspose2d(in_channels=1,
                    out_channels=1,
                    kernel_size=3,
                    stride=2,
                    padding=0)

In [5]:
m.weight

Parameter containing:
tensor([[[[-0.1252,  0.2197,  0.1881],
          [ 0.0638, -0.2103,  0.2227],
          [ 0.1585,  0.1150, -0.1670]]]], requires_grad=True)

In [6]:
m.bias

Parameter containing:
tensor([0.2719], requires_grad=True)

In [7]:
with torch.no_grad():
    m.weight.data=nn.Parameter(torch.tensor([[[[1,1,1],
                          [1,1,1],
                          [1,1,1]]]],dtype=torch.float32))
    m.bias.data=nn.Parameter(torch.tensor([0.0]))

In [8]:
m.weight

Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)

In [9]:
m(img.reshape(1,1,2,2).float())

tensor([[[[ 1.,  1.,  3.,  2.,  2.],
          [ 1.,  1.,  3.,  2.,  2.],
          [ 4.,  4., 10.,  6.,  6.],
          [ 3.,  3.,  7.,  4.,  4.],
          [ 3.,  3.,  7.,  4.,  4.]]]], grad_fn=<SlowConvTranspose2DBackward>)